# Generated by Django 4.2.2 on 2026-10-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=32, null=True)),
                ('customer_telno', models.CharField(blank=True, max_length=13, null=True)),
                ('customer_postalcode', models.CharField(blank=True, max_length=8, null=True)),
                ('customer_address', models.CharField(blank=True, max_length=40, null=True)),
                ('discount_rate', models.IntegerField(blank=True, null=True)),
                ('delete_flag', models.IntegerField()),
            ],
            options={
                'db_table': 'customer',
                'managed': True,
            },
        ),
    ]
