# Generated by Django 4.2.2 on 2026-10-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_book_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_no', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
